function Video_matrix = ReadPhantomFile(Header_info,Full_header_name)
%% Function to read image data from Phantom cine file
% Written by Anirudh Thuppul 04/21/2020
% Last edited by Anirudh Thuppul 04/27/2020
% Inputs:
% - Header_info: object generated by ReadPhantomHeader with video info
% - Full_header_name: Filename of xml header file including path info
% Output:
% - Video_matrix: Matrix containing frame image values

% Open video file and extract important information
Cine_file_name = strcat(Full_header_name(1:end-4),'.cine');
Cine_file_info = dir(Cine_file_name);
Cine_file = fopen(Cine_file_name,'r','l');
Image_size = Header_info.Frame_width*Header_info.Frame_height;
Total_image_size = Header_info.Num_frames*Image_size;
disp(['Importing cine file with ' num2str(Header_info.Num_frames) ' frames'])

% Read video frames
Junk = Cine_file_info.bytes/2-(Header_info.Num_frames-1)*4-Total_image_size;
Bad = fread(Cine_file,Junk,'ubit16=>int32');
Good = fread(Cine_file,Image_size,'ubit16=>int32');
Good2 = rot90(reshape(Good,Header_info.Frame_width,Header_info.Frame_height),3);
Frames = zeros(Header_info.Frame_height,Header_info.Frame_width,Header_info.Num_frames,'int32');
Frames(:,:,1) = Good2;
for i = 2:Header_info.Num_frames
    Bad2 = fread(Cine_file,4,'ubit16=>int32');
    Good3 = fread(Cine_file,Image_size,'ubit16=>int32');
    Good3 = rot90(reshape(Good3,Header_info.Frame_width,Header_info.Frame_height),3);
    Frames(:,:,i) = Good3;
end
Video_matrix = Frames;

end